### ISSUE TITLE
Impossible to run RogueEditor

### ISSUE THREAD

**Issue by Devitsune** [M6D6M6A/PokeRogueBot#1] opened 2024-05-29 08:57 UTC
Maybe i do something wrong but i run "run.py" and then i connect my account, i select "Run RogueEditor" but i can't use it i have always the same message : Command: 11
![Capture d’écran 2024-05-29 105420](https://github.com/molker/pokerogue-utility/assets/137762751/54c94a95-177c-4cd4-95d4-2cd9cdfe490d)
![Capture d’écran 2024-05-29 105449](https://github.com/molker/pokerogue-utility/assets/137762751/87268fb6-0fa1-4edf-ad73-d0c18c5c975d)
But thanks for you work :)

**Comment by M6D6M6A** [comment] 2024-05-29 09:10
Hey, ty it was a bug caused by the find and replace feature, it was `self.self.UPDATE_TRAINER_DATA_URL` instead of `self.UPDATE_TRAINER_DATA_URL`, i updated the code and its fixed now. :)

**Comment by Devitsune** [comment] 2024-05-29 09:23
Fine it works but for the eggs hatch i have to do it manually on the trainer.json, can't use "1: Hatch all eggs. " :)

**Comment by M6D6M6A** [comment] 2024-05-29 09:26
I actually never used this feature yet, its the original function, I can check if I can find some bug. :)

**Comment by M6D6M6A** [comment] 2024-05-29 09:36
The function had a wired check, it would grab the trainer data from the server, then use the logic to hatch the eggs, then it would grab the data from the server again with `self.get_trainer_data()` but did not use the data at all and at the end it checked if the modified data is None, and only if thats true, it would upload the result. This made no sesne and i checked the original repo, the if check was not in the latest version, so i deleted it aswell and commented out the second request from the server, since it did not make sense imo. Itr should be fiexed no, if you have other problems, just let me know. :)

**Comment by Devitsune** [comment] 2024-05-29 11:39
Thx it work nice now. good job =D

**Closed** 2024-05-29 14:04 UTC
